# Site Settings
encoding                 : "utf-8"
locale                   : "en"
title                    : "Justin Browning"
description              : "Mathematics Graduate Student @ The University of North Texas"
favicon                  : "https://media.licdn.com/dms/image/C5603AQGKALEUPL0R7A/profile-displayphoto-shrink_800_800/0/1607909842936?e=1724889600&v=beta&t=4V9zuCEIe_-tod9G814qX2mEF_P20m89vruSKyt51mg"
avatar                   : "https://media.licdn.com/dms/image/C5603AQGKALEUPL0R7A/profile-displayphoto-shrink_800_800/0/1607909842936?e=1724889600&v=beta&t=4V9zuCEIe_-tod9G814qX2mEF_P20m89vruSKyt51mg"
baseurl                  : "" # the subpath of your site, e.g. "/blog" leave blank if no subpath

publish_mode: editorial_workflow # required for Netlify
future: true # if the post's date is in the future

# Site Author
author:
  name                   : "Justin Browning" # appears in the footer and atom feed

comments                 : true # set it to false to disable comments
disqus:
  shortname              : # https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-

atom_feed:
  path                   : # blank (default) uses feed.xml

og_image                 : "/assets/images/mighil.png" # Open Graph/Twitter default site image, optional for seo and social sharing

# Social sharing
twitter:
  username               : # optional, for social sharing

# Analytics
analytics:
  google:
    tracking_id          :  # add your google tracking id here

# Reading Files
include:
  - _pages
  - "_redirects"
# Files excluded from Jekyll builds
exclude:
- README.md
- LICENSE
- Gemfile
- Gemfile.lock


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  math_engine: mathjax
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:title/
paginate: 5 # amount of posts to show
paginate_path: "/blog/page:num/"
timezone: US # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

collections:
  poetry:
    output: true
    permalink: /:collection/:title/

# Plugins
gems:
  - jekyll-paginate
  - jekyll-feed

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-feed


# Front matter defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      comments: false
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      share: true
  # _poetry
  - scope:
      path: ""
      type: poetry
    values:
      layout: post
      share: false
  # _exclude    
exclude:
         - vendor
         - Gemfile
         - Gemfile.lock
         - node_modules
         - gulpfile.js
         - package.json      
